import pandas as pd

# Define a list of 100 distinct cancer genes with their details
gene_data = [
    {"Gene Name": "TP53", "Associated Cancer": "Various (breast, lung, colon)", "Pathway Involved": "Cell Cycle Regulation & Apoptosis", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "KRAS", "Associated Cancer": "Pancreatic, colon, lung", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "EGFR", "Associated Cancer": "Non-small cell lung cancer", "Pathway Involved": "EGFR Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PIK3CA", "Associated Cancer": "Breast, colorectal", "Pathway Involved": "PI3K/AKT Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PTEN", "Associated Cancer": "Endometrial, prostate", "Pathway Involved": "PI3K/AKT/mTOR Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "BRCA1", "Associated Cancer": "Breast, ovarian", "Pathway Involved": "DNA Repair (Homologous Recombination)", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "BRCA2", "Associated Cancer": "Breast, ovarian", "Pathway Involved": "DNA Repair (Homologous Recombination)", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ALK", "Associated Cancer": "Lung", "Pathway Involved": "ALK Fusion Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "BRAF", "Associated Cancer": "Melanoma, colorectal", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NRAS", "Associated Cancer": "Melanoma, hematologic", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MET", "Associated Cancer": "Lung, papillary renal", "Pathway Involved": "MET Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "RET", "Associated Cancer": "Thyroid, lung", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CDKN2A", "Associated Cancer": "Melanoma, pancreatic", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "RB1", "Associated Cancer": "Retinoblastoma", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "APC", "Associated Cancer": "Colorectal", "Pathway Involved": "Wnt/β-catenin Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CTNNB1", "Associated Cancer": "Hepatocellular, colorectal", "Pathway Involved": "Wnt/β-catenin Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "SMAD4", "Associated Cancer": "Pancreatic", "Pathway Involved": "TGF-β Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGFR1", "Associated Cancer": "Lung, breast", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGFR2", "Associated Cancer": "Breast, endometrial", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGFR3", "Associated Cancer": "Bladder", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGFR4", "Associated Cancer": "Rhabdomyosarcoma", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "KIT", "Associated Cancer": "Gastrointestinal stromal tumor", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PDGFRA", "Associated Cancer": "Gastrointestinal stromal tumor", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PDGFRB", "Associated Cancer": "Dermatofibrosarcoma", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "JAK2", "Associated Cancer": "Myeloproliferative neoplasms", "Pathway Involved": "JAK/STAT Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "STAT3", "Associated Cancer": "Various", "Pathway Involved": "JAK/STAT Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MYC", "Associated Cancer": "Various", "Pathway Involved": "Transcription Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MDM2", "Associated Cancer": "Sarcoma", "Pathway Involved": "p53 Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CDK4", "Associated Cancer": "Melanoma", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CCND1", "Associated Cancer": "Breast, head and neck", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CCNE1", "Associated Cancer": "Ovarian", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "AR", "Associated Cancer": "Prostate", "Pathway Involved": "Androgen Receptor Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ESR1", "Associated Cancer": "Breast", "Pathway Involved": "Estrogen Receptor Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ERBB2", "Associated Cancer": "Breast", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ERBB3", "Associated Cancer": "Breast", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NOTCH1", "Associated Cancer": "T-cell leukemia", "Pathway Involved": "Notch Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NOTCH2", "Associated Cancer": "B-cell lymphoma", "Pathway Involved": "Notch Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NOTCH3", "Associated Cancer": "Ovarian", "Pathway Involved": "Notch Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "SMARCB1", "Associated Cancer": "Rhabdoid tumor", "Pathway Involved": "Chromatin Remodeling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NF1", "Associated Cancer": "Neurofibromatosis, glioma", "Pathway Involved": "RAS/MAPK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NF2", "Associated Cancer": "Schwannoma", "Pathway Involved": "Hippo Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "TERT", "Associated Cancer": "Various", "Pathway Involved": "Telomere Maintenance", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "IDH1", "Associated Cancer": "Glioma", "Pathway Involved": "Metabolic Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "IDH2", "Associated Cancer": "Acute myeloid leukemia", "Pathway Involved": "Metabolic Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "TET2", "Associated Cancer": "Myelodysplastic syndrome", "Pathway Involved": "Epigenetic Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "DNMT3A", "Associated Cancer": "Acute myeloid leukemia", "Pathway Involved": "DNA Methylation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ASXL1", "Associated Cancer": "Myelodysplastic syndrome", "Pathway Involved": "Epigenetic Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "EZH2", "Associated Cancer": "Lymphoma", "Pathway Involved": "Histone Methylation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "SETD2", "Associated Cancer": "Renal cell carcinoma", "Pathway Involved": "Histone Methylation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "SF3B1", "Associated Cancer": "Myelodysplastic syndrome", "Pathway Involved": "RNA Splicing", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "SRSF2", "Associated Cancer": "Myelodysplastic syndrome", "Pathway Involved": "RNA Splicing", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "U2AF1", "Associated Cancer": "Myelodysplastic syndrome", "Pathway Involved": "RNA Splicing", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PPM1D", "Associated Cancer": "Breast", "Pathway Involved": "p53 Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "USP7", "Associated Cancer": "Various", "Pathway Involved": "Protein Deubiquitination", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CSF1R", "Associated Cancer": "Histiocytosis", "Pathway Involved": "Receptor Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ABL1", "Associated Cancer": "Chronic myeloid leukemia", "Pathway Involved": "Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "ROS1", "Associated Cancer": "Non-small cell lung cancer", "Pathway Involved": "Tyrosine Kinase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NTRK1", "Associated Cancer": "Various", "Pathway Involved": "Neurotrophin Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NTRK2", "Associated Cancer": "Various", "Pathway Involved": "Neurotrophin Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "NTRK3", "Associated Cancer": "Various", "Pathway Involved": "Neurotrophin Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "KMT2A", "Associated Cancer": "Acute lymphoblastic leukemia", "Pathway Involved": "Chromatin Remodeling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "KMT2D", "Associated Cancer": "Follicular lymphoma", "Pathway Involved": "Chromatin Remodeling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "BRD4", "Associated Cancer": "NUT midline carcinoma", "Pathway Involved": "Transcription Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CCND2", "Associated Cancer": "Breast", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CCND3", "Associated Cancer": "Lymphoma", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CDKN1B", "Associated Cancer": "Breast", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CDKN2B", "Associated Cancer": "Glioblastoma", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CDKN2C", "Associated Cancer": "Multiple myeloma", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "AKT1", "Associated Cancer": "Breast", "Pathway Involved": "PI3K/AKT Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "AKT2", "Associated Cancer": "Pancreatic", "Pathway Involved": "PI3K/AKT Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "AKT3", "Associated Cancer": "Melanoma", "Pathway Involved": "PI3K/AKT Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "mTOR", "Associated Cancer": "Various", "Pathway Involved": "mTOR Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "GNAS", "Associated Cancer": "Pituitary", "Pathway Involved": "G-Protein Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "VHL", "Associated Cancer": "Renal cell carcinoma", "Pathway Involved": "Hypoxia Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "HIF1A", "Associated Cancer": "Various", "Pathway Involved": "Hypoxia Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CCNE2", "Associated Cancer": "Ovarian", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "AURKA", "Associated Cancer": "Breast", "Pathway Involved": "Mitotic Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "AURKB", "Associated Cancer": "Colorectal", "Pathway Involved": "Mitotic Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PLK1", "Associated Cancer": "Various", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "BCL2", "Associated Cancer": "Lymphoma", "Pathway Involved": "Apoptosis Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MCL1", "Associated Cancer": "Multiple myeloma", "Pathway Involved": "Apoptosis Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGF19", "Associated Cancer": "Hepatocellular carcinoma", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGF3", "Associated Cancer": "Breast", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGF4", "Associated Cancer": "Embryonal", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGF8", "Associated Cancer": "Prostate", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "FGF10", "Associated Cancer": "Lung", "Pathway Involved": "FGF Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MAP2K1", "Associated Cancer": "Melanoma", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MAP2K2", "Associated Cancer": "Lung", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MAPK1", "Associated Cancer": "Various", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "MAPK3", "Associated Cancer": "Various", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "RAF1", "Associated Cancer": "Various", "Pathway Involved": "MAPK/ERK Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "RHOA", "Associated Cancer": "Gastric", "Pathway Involved": "Rho GTPase Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "SMO", "Associated Cancer": "Basal cell carcinoma", "Pathway Involved": "Hedgehog Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "GLI1", "Associated Cancer": "Glioma", "Pathway Involved": "Hedgehog Signaling", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CCNB1", "Associated Cancer": "Breast", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PLK4", "Associated Cancer": "Colorectal", "Pathway Involved": "Cell Cycle Regulation", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CHEK1", "Associated Cancer": "Breast", "Pathway Involved": "DNA Damage Response", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "CHEK2", "Associated Cancer": "Breast", "Pathway Involved": "DNA Damage Response", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "PARP1", "Associated Cancer": "Ovarian", "Pathway Involved": "DNA Repair", "Reference": "COSMIC Cancer Gene Census"},
    {"Gene Name": "XRCC1", "Associated Cancer": "Lung", "Pathway Involved": "DNA Repair", "Reference": "COSMIC Cancer Gene Census"}
]

# Create the DataFrame
df = pd.DataFrame(gene_data)

# Display the first few rows of the DataFrame
print(df.head())

# Optionally, save the dataset to a CSV file:
df.to_csv("cancer_gene_data_100.csv", index=False)
